name = 'MyPaint Website Theme'
license = 'MIT'
licenselink = 'https://github.com/mypaint/website-theme/LICENSE'
description = "The theme of MyPaint's website"

# The home page of the theme, where the source can be found
homepage = 'https://github.com/mypaint/website-theme'

# If you have a running demo of the theme
demosite = 'https://mypaint.org/'

# If the theme has multiple authors
authors = [
  {name = 'Aesara Binder', homepage = 'https://www.aesara.net/'}
]
